title: Akarsh Website
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"

# social links
github_username:  akkssup # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

